[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.build]
cmds = [
  "pnpm install",
  "cd client && pnpm install",
  "rm -rf client/dist",
  "pnpm run build"
]

[start]
cmd = "node dist/index.js"
